# Generated by Django 5.2.4 on 2025-08-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField()),
                ('rides_count', models.IntegerField()),
                ('color_class', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=50)),
            ],
        ),
    ]
